"""create_initial_tables

Revision ID: 5a80c1834ea0
Revises: 
Create Date: 2025-05-09 12:43:49.324875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a80c1834ea0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_google_tokens',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_uri', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('client_secret', sa.String(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('user_email')
    )
    with op.batch_alter_table('user_google_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_google_tokens_user_email'), ['user_email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_google_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_google_tokens_user_email'))

    op.drop_table('user_google_tokens')
    # ### end Alembic commands ###
