services:
  mailapi:
    build: ./mailapi
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./mailapi:/app/server/mailapi
      - ./shared:/app/server/shared
      - ./mailapi/.env:/app/server/mailapi/.env:ro
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/mailapi
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - PYTHONPATH=/app:/app/server:/app/server/mailapi
      - RESTATE_URL=http://host.docker.internal:8080
    depends_on:
      - db

  python-hello-world:
    build: ./restate_services/python-hello-world
    ports:
      - "9080:9080"
    working_dir: /usr/src/app
    volumes:
      - ./restate_services/python-hello-world:/usr/src/app
      - ./shared:/usr/src/app/shared
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/mailapi
      - PYTHONPATH=/usr/src/app:/usr/src/app/src
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mailapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: